### ISSUE TITLE
Error in global md 🙂😥

### ISSUE THREAD

**Issue by GG-GLITCH1** [GlobalTechInfo/GLOBAL-MD#10]
Hello qasim nice work on global md ..but I'm stuck in the big world of error requiring module node js not found in file ..but global bug ..is so straight forward ..no single eror s at all 😍😎..if you can message me here lemme show you the error logs on whatsapp ..i will be happy brr, qasim Ali 2348148252474 ....noted !

**Comment by GlobalTechInfo** [comment]
update fork and try it again now it's working

**Comment by GG-GLITCH1** [comment]
Okay brotha ..
